# Generated by Django 4.2.1 on 2023-06-19 15:01

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('description', ckeditor.fields.RichTextField(verbose_name='description')),
                ('short_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='short description')),
                ('digital', models.BooleanField(blank=True, default=False, null=True, verbose_name='digital')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('discount', models.BooleanField(default=False, verbose_name='discount')),
                ('discount_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='discount price')),
                ('discount_timer', models.DateTimeField(blank=True, null=True, verbose_name='discount timer')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('slug_change', models.BooleanField(default=False, help_text='If you want change the slug by name', verbose_name='slug change')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text="If field be empty it's automatic change by name ", max_length=300, verbose_name='slug')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='datetime created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='datetime modified')),
                ('favorite', models.ManyToManyField(blank=True, default=None, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_like', models.DateTimeField(auto_now_add=True, verbose_name='datetime like')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datetime_like', to='products.product', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datetime_like', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
