# Generated by Django 4.2.1 on 2023-06-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover',
            field=models.ImageField(default='null', upload_to='product_covers/', verbose_name='cover'),
            preserve_default=False,
        ),
    ]
