# Generated by Django 4.2.1 on 2023-06-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug_change', models.BooleanField(help_text='If you want change the slug by name', verbose_name='slug change')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text="If field be empty it's automatic change by name ", max_length=300, verbose_name='slug')),
            ],
        ),
    ]
