# Generated by Django 4.2.1 on 2023-06-19 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('star', models.CharField(choices=[('1', 'Too Bad'), ('2', 'Bad'), ('3', 'Normal'), ('4', 'Good'), ('5', 'Great')], max_length=1, verbose_name='star')),
                ('edited', models.BooleanField(default=False, verbose_name='edited')),
                ('confirmation', models.BooleanField(default=False, verbose_name='confirmation')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='datetime created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='datetime modified')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product', verbose_name='product')),
            ],
        ),
    ]
