# Generated by Django 4.2.1 on 2023-06-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, blank=True, help_text="If field be empty it's automatic change by name ", max_length=300, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_fa',
            field=models.SlugField(allow_unicode=True, blank=True, help_text="If field be empty it's automatic change by name ", max_length=300, null=True, verbose_name='slug'),
        ),
    ]
